---
title: "Find_Yoga_Proxies"
author: "Melissa Wong"
date: "November 2, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(out.width = "50%")
#knitr::opts_chunk$set(eval = FALSE)
#knitr::opts_chunk$set(fig.align = "center")

library(tidyverse)

source("../src_lenovo_project.R")
source("data_prep.R")
```

```{r}
filter_raw_data()

load("../CleanData/filtered_sentiment_data.Rdata")
```

# YOGA C930

## Monthly
```{r}
# Look at Yoga products by Month
yoga <- sentiment.consumer.all %>%
  filter(grepl('YOGA', ProductName)) %>%
 group_by(ProductName,
           month = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg))

par(mfrow=c(1,2))
for (i in unique(yoga$ProductName))
{
  print(
    ggplot() +
      geom_line(data=yoga[yoga$ProductName==i,],
              mapping = aes(x=month, y=psi, colour=i)) +
      geom_line(data=yoga[yoga$ProductName=="YOGA C930",],
              mapping = aes(x=month, y=psi, colour="YOGA C930")) +
      labs(title="PSI by month compared ot YOGA C930") +
      theme(legend.position = "bottom")
  )
}
```

## Weekly

```{r}
# Look at Yoga products by Week
yoga <- sentiment.consumer.all %>%
  filter(grepl('YOGA', ProductName)) %>%
 group_by(ProductName,
           month = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "week")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg))

par(mfrow=c(1,2))
for (i in unique(yoga$ProductName))
{
  print(
    ggplot() +
      geom_line(data=yoga[yoga$ProductName==i,],
              mapping = aes(x=month, y=psi, colour=i)) +
      geom_line(data=yoga[yoga$ProductName=="YOGA C930",],
              mapping = aes(x=month, y=psi, colour="YOGA C930")) +
      labs(title="PSI by week compared ot YOGA C930") +
      theme(legend.position = "bottom")
  )
}
```

# YOGA 730

## Monthly
```{r}
# Look at Yoga products by Month
yoga <- sentiment.consumer.all %>%
  filter(grepl('YOGA', ProductName)) %>%
 group_by(ProductName,
           month = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg))

par(mfrow=c(1,2))
for (i in unique(yoga$ProductName))
{
  print(
    ggplot() +
      geom_line(data=yoga[yoga$ProductName==i,],
              mapping = aes(x=month, y=psi, colour=i)) +
      geom_line(data=yoga[yoga$ProductName=="YOGA 730 15",],
              mapping = aes(x=month, y=psi, colour="YOGA 730 15")) +
      geom_line(data=yoga[yoga$ProductName=="YOGA 730 13",],
              mapping = aes(x=month, y=psi, colour="YOGA 730 13")) +
      labs(title="PSI by month compared to YOGA C730") +
      theme(legend.position = "bottom")
  )
}
```

## Weekly

```{r}
# Look at Yoga products by Week
yoga <- sentiment.consumer.all %>%
  filter(grepl('YOGA', ProductName)) %>%
 group_by(ProductName,
           month = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "week")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg))

par(mfrow=c(1,2))
for (i in unique(yoga$ProductName))
{
  print(
    ggplot() +
      geom_line(data=yoga[yoga$ProductName==i,],
              mapping = aes(x=month, y=psi, colour=i)) +
      geom_line(data=yoga[yoga$ProductName=="YOGA 730 15",],
              mapping = aes(x=month, y=psi, colour="YOGA 730 15")) +
      geom_line(data=yoga[yoga$ProductName=="YOGA 730 13",],
              mapping = aes(x=month, y=psi, colour="YOGA 730 13")) +
      labs(title="PSI by week compared to YOGA C730") +
      theme(legend.position = "bottom")
  )
}
```

