---
title: "POM_Analysis_Month"
author: "Melissa Wong"
date: \today
output: pdf_document
---

```{r setup, include=FALSE}
rm(list = ls())

#knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(out.width = "50%")
#knitr::opts_chunk$set(eval = FALSE)
#knitr::opts_chunk$set(fig.align = "center")

library(tidyverse)
library(VGAM) # for vglm
library(MASS) # for polr

#source("../src_lenovo_project.R")
source("data_prep.R")
```

```{r}
filter_raw_data()

load("../CleanData/filtered_sentiment_data.Rdata")
load("../CleanData/filtered_product_lists.Rdata")
load("../CleanData/filtered_survey_data.Rdata")
```

# Proportional Odd Model

## Prepare data (Consumer Only)
```{r}
tmp <- sentiment.consumer %>%
  group_by(ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE"),
            stars = mean(Stars.Rating)) %>%
  mutate(psi = ifelse(pos == 0 & neg == 0, 0, 100 * (pos - neg)/(pos +  neg)))

hist(tmp$psi)
quantile(tmp$psi, seq(0,1,0.2))
```

```{r}

# Calculate PSI by month and by product
psi <- sentiment.consumer %>%
  group_by(ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE"),
            stars = mean(Stars.Rating)) %>%
  mutate(psi = ifelse(pos == 0 & neg == 0, 0, 100 * (pos - neg)/(pos +  neg))) %>%
  mutate(psi_cat = case_when((psi <= 0) ~ -50.0,
                             (0 < psi & psi <= 30) ~ 15.0,
                             (30 < psi & psi <= 60) ~ 45.0,
                             (60 < psi & psi <= 90) ~ 75.0,
                             (90 < psi) ~ 95.0),
         star_cat = case_when((stars < 2.5) ~ "NEGATIVE",
                              (2.5 <= stars & stars < 3.5) ~ "NEUTRAL",
                              (3.5 <= stars) ~ "POSITIVE"))

# Calculate NPS by month and by product
nps <- survey.consumer %>%
  group_by(ProductName,
           time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "month")) %>%
  summarise(promoter = sum(NPS >= 9),
            detractor = sum(NPS <= 6),
            total = n()) %>%
  mutate(nps = 100 * (promoter - detractor) / total) %>%
  mutate(nps_cat = case_when((nps <= 8 ~ "VERY_LOW"),
                             (8 < nps & nps <=35) ~ "MOD_LOW",
                             (35 < nps & nps <=45) ~ "NORMAL",
                             (45 < nps & nps <= 60) ~ "MOD_HIGH",
                             (60 < nps) ~ "VERY_HIGH"))

tmp <- merge(nps, psi, all=T)
```

```{r}

# Remove rows if nps or psi = NA and spread into wide format
tmp_clean <- tmp %>%
  filter(!is.na(nps) & !is.na(psi)) %>%
  dplyr::select(ProductName, psi_cat, star_cat, nps_cat) %>%
  ungroup()

tmp_wide <- tmp_clean %>%
  group_by(psi_cat, star_cat, nps_cat) %>%
  summarise(count = n()) %>%
  spread(nps_cat, count, fill=0)

tmp_wide

```

```{r}
# tmp_wide$psi_cat = factor(tmp_wide$psi_cat, levels = c("VERY_LOW", "MOD_LOW",
#                        "NORMAL", "MOD_HIGH", "VERY_HIGH"))

tmp_wide$star_cat = factor(tmp_wide$star_cat, levels = c("NEGATIVE", "NEUTRAL", "POSITIVE"))

pom <- vglm(cbind(VERY_LOW, MOD_LOW, NORMAL, 
                  MOD_HIGH, VERY_HIGH) ~ psi_cat + star_cat, 
            data = tmp_wide,
            family = cumulative(parallel = TRUE))

summary(pom)
```


```{r}
# Estimated response probabilities for each group
data.frame(PSI = tmp_wide$psi_cat, Stars=tmp_wide$star_cat, fitted(pom))

```

## Collapse duplicate sentiment by rater

```{r}

# Calculate PSI by month and by product
psi <- sentiment.consumer %>%
  group_by(ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month"),
           Comment, Stars.Rating) %>%
  summarize(rater_pos = sum(Sentiment == "POSITIVE"),
            rater_neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(rater_psi = ifelse(rater_pos == 0 & rater_neg == 0, 0, 
                            100 * (rater_pos - rater_neg)/(rater_pos +  rater_neg))) %>%
  ungroup() %>%
  group_by(ProductName, time) %>%
  summarise(pos = sum(rater_pos),
            neg = sum(rater_neg),
            psi = mean(rater_psi, na.rm = TRUE),
            stars = mean(Stars.Rating)) %>%
  mutate(psi_cat = case_when((psi <= 0) ~ -50.0,
                             (0 < psi & psi <= 30) ~ 15.0,
                             (30 < psi & psi <= 60) ~ 45.0,
                             (60 < psi & psi <= 90) ~ 75.0,
                             (90 < psi) ~ 95.0),
         star_cat = case_when((stars < 2.5) ~ "NEGATIVE",
                              (2.5 <= stars & stars < 3.5) ~ "NEUTRAL",
                              (3.5 <= stars) ~ "POSITIVE"))

# Calculate NPS by month and by product
nps <- survey.consumer %>%
  group_by(ProductName,
           time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "month")) %>%
  summarise(promoter = sum(NPS >= 9),
            detractor = sum(NPS <= 6),
            total = n()) %>%
  mutate(nps = 100 * (promoter - detractor) / total) %>%
  mutate(nps_cat = case_when((nps <= 8 ~ "VERY_LOW"),
                             (8 < nps & nps <=35) ~ "MOD_LOW",
                             (35 < nps & nps <=45) ~ "NORMAL",
                             (45 < nps & nps <= 60) ~ "MOD_HIGH",
                             (60 < nps) ~ "VERY_HIGH"))

tmp <- merge(nps, psi, all=T)

# Remove rows if nps or psi = NA and spread into wide format
tmp_clean <- tmp %>%
  filter(!is.na(nps) & !is.na(psi)) %>%
  dplyr::select(ProductName, psi_cat, star_cat, nps_cat) %>%
  ungroup()

tmp_wide <- tmp_clean %>%
  group_by(psi_cat, star_cat, nps_cat) %>%
  summarise(count = n()) %>%
  spread(nps_cat, count, fill=0)

tmp_wide
```

```{r}
# tmp_wide$psi_cat = factor(tmp_wide$psi_cat, levels = c("VERY_LOW", "MOD_LOW",
#                        "NORMAL", "MOD_HIGH", "VERY_HIGH"))

tmp_wide$star_cat = factor(tmp_wide$star_cat, levels = c("NEGATIVE", "NEUTRAL", "POSITIVE"))

pom.1 <- vglm(cbind(VERY_LOW, MOD_LOW, NORMAL, 
                  MOD_HIGH, VERY_HIGH) ~ psi_cat + star_cat, 
            data = tmp_wide,
            family = cumulative(parallel = TRUE))

summary(pom.1)
```
```{r}
pchisq(54.7471, 45, lower.tail = FALSE)
```

```{r}
# Estimated response probabilities for each group
data.frame(PSI = tmp_wide$psi_cat, Stars=tmp_wide$star_cat, fitted(pom.1))

```


```{r}
# Verify I get same results with polr

tmp_long <- tmp_clean %>%
  group_by(psi_cat, star_cat, nps_cat) %>%
  summarise(count = n()) 

tmp_long$nps_cat = factor(tmp_long$nps_cat, levels = c("VERY_LOW", "MOD_LOW",
                        "NORMAL", "MOD_HIGH", "VERY_HIGH"))

tmp_long$star_cat = factor(tmp_long$star_cat, levels = c("NEGATIVE", "NEUTRAL", "POSITIVE"))

pom.polr <- polr(nps_cat ~ psi_cat + star_cat, data=tmp_long, weight=count)

summary(pom.polr)
```

## Model with just PSI as predictor

```{r}
tmp_wide2 <- tmp_clean %>%
  group_by(psi_cat, nps_cat) %>%
  summarise(count = n()) %>%
  spread(nps_cat, count, fill=0)

pom.2 <- vglm(cbind(VERY_LOW, MOD_LOW, NORMAL, 
                  MOD_HIGH, VERY_HIGH) ~ psi_cat, 
            data = tmp_wide2,
            family = cumulative(parallel = TRUE))

summary(pom.2)
```


```{r}
pchisq(54.7-28.7, 45-15, lower.tail=FALSE)
```

```{r}
# Estimated response probabilities for each group
fitted(pom.2)
```

## Model with interaction term

```{r}
pom.3 <- vglm(cbind(VERY_LOW, MOD_LOW, NORMAL, 
                  MOD_HIGH, VERY_HIGH) ~ psi_cat + star_cat + psi_cat:star_cat, 
            data = tmp_wide,
            family = cumulative(parallel = TRUE))

summary(pom.3)
```

```{r}
pchisq(48.7, 43)
```

```{r}
lrtest(pom.1, pom.3)
```

```{r}
# Estimated response probabilities for each group
data.frame(PSI = tmp_wide$psi_cat, Stars=tmp_wide$star_cat, fitted(pom.3))
```

## Baseline Category
```{r}
# Baseline category fit
baseline <- vglm(cbind(VERY_LOW, MOD_LOW, NORMAL, 
                 MOD_HIGH, VERY_HIGH) ~ psi_cat + star_cat, 
                 data = tmp_wide,
#                 family = cumulative)
                 family = multinomial(refLevel = "VERY_LOW"))

summary(baseline)
```
```{r}
lrtest(baseline, pom.1)
lrtest(baseline, pom.3)
# POM is better fit than baseline category
```
