---
title: "Remove_dups"
author: "Melissa Wong"
date: "November 2, 2019"
output: pdf_document
---


```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(out.width = "50%")
knitr::opts_chunk$set(fig.align = "center")

library(tidyverse)

source("../src_lenovo_project.R")
source("data_prep.R")
```


```{r}
filter_raw_data()

load("../CleanData/filtered_sentiment_data.Rdata")
load("../CleanData/filtered_survey_data.Rdata")
load("../CleanData/filtered_product_lists.Rdata")

```

Calculate PSI the usual way:

$$PSI = 100 * \frac{pos - neg}{pos + neg}$$

```{r}
# Calculate PSI by month and by product
comm.psi.month_prod <- sentiment.comm %>%
  group_by(ProductName,
           month = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg))
```

Calculate a per rater PSI and then get mean PSI by group (in this case Product and Month):

```{r}
# Group by comments to get an idea of how duplicates affect sentiment
comm.psi.comments <- sentiment.comm %>%
  group_by(ProductName, 
           month = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month"),
           Comment, Stars.Rating) %>%
  summarize(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(rater_psi = 100 * (pos - neg)/(pos +  neg)) %>%
  ungroup() %>%
  group_by(ProductName, month) %>%
  summarise(psi = mean(rater_psi, na.rm = TRUE)) 

```

# Plot for comparison
```{r}

for (i in unique(comm.psi.month_prod$ProductName))
{
  print(ggplot() +
    geom_line(data=comm.psi.month_prod[comm.psi.month_prod$ProductName==i,],
              mapping = aes(x=month, y=psi, colour="Original PSI")) +
    geom_line(data=comm.psi.comments[comm.psi.comments$ProductName==i,],
              mapping = aes(x=month, y=psi, colour="Mean Rater PSI")) +
    labs(title=paste("PSI for Product ",i)))
}
```

