---
title: "Transitions2.Rmd"
author: "Melissa Wong"
date: "November 16, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
rm(list = ls())

#knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(out.width = "50%")
#knitr::opts_chunk$set(eval = FALSE)
#knitr::opts_chunk$set(fig.align = "center")

library(tidyverse)

source("data_prep.R")
source("helper_calcs.R")
```

```{r}
filter_raw_data()

load("../CleanData/filtered_sentiment_data.Rdata")
load("../CleanData/filtered_product_lists.Rdata")
load("../CleanData/filtered_survey_data.Rdata")
```

# PSI Transitions

## Commercial

### By Week

```{r}

tmp <- sentiment.comm.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "week")) %>%
  calcPSI()

hist(tmp$psi)
quantile(tmp$psi, seq(0,1,0.2))
```

```{r}
# Define PSI categories
VERY_HIGH <- 68.0
MOD_HIGH <- 62.0
NORMAL <- 44.0
MOD_LOW <- 34.0

res <- sentiment.comm.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "week")) %>% 
  PSITransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Weekly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Weekly")
```

### Semi-Monthly

```{r}
tmp <- sentiment.comm.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "year"),
           week2 = ceiling(week(as.Date(Comment.Date, format = "%m/%d/%y"))/2)) %>%
  calcPSI()

hist(tmp$psi)
quantile(tmp$psi, seq(0,1,0.2))
```

```{r}
# Define PSI categories
VERY_HIGH <- 68.0
MOD_HIGH <- 62.0
NORMAL <- 44.0
MOD_LOW <- 34.0

res <- sentiment.comm.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "year"),
           week2 = ceiling(week(as.Date(Comment.Date, format = "%m/%d/%y"))/2)) %>%
  PSITransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Semi-Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Semi-Monthly")
```

### By Month

```{r}
tmp <- sentiment.comm.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  calcPSI()

hist(tmp$psi)
quantile(tmp$psi, seq(0,1,0.2))
```


```{r}
# Define PSI categories
VERY_HIGH <- 67.0
MOD_HIGH <- 63.0
NORMAL <- 47.0
MOD_LOW <- 36.0

res <- sentiment.comm.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  PSITransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Monthly")
```




## Consumer

### By Week


```{r}

tmp <- sentiment.consumer.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "week")) %>%
  calcPSI()

hist(tmp$psi)
quantile(tmp$psi, seq(0,1,0.2))
```

```{r}
# Define PSI categories
VERY_HIGH <- 65.0
MOD_HIGH <- 60.0
NORMAL <- 45.0
MOD_LOW <- 42.0

res <- sentiment.consumer.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "week")) %>%
  PSITransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Monthly")
```

### Semi-Monthly

```{r}
tmp <- sentiment.consumer.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "year"),
           week2 = ceiling(week(as.Date(Comment.Date, format = "%m/%d/%y"))/2)) %>%
  calcPSI()

hist(tmp$psi)
quantile(tmp$psi, seq(0,1,0.2))
```

```{r}
# Define PSI categories
VERY_HIGH <- 66.0
MOD_HIGH <- 61.0
NORMAL <- 46.0
MOD_LOW <- 41.0

res <- sentiment.consumer.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "year"),
           week2 = ceiling(week(as.Date(Comment.Date, format = "%m/%d/%y"))/2)) %>%
  PSITransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Semi-Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Semi-Monthly")
```

### By Month


```{r}

tmp <- sentiment.consumer.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  calcPSI()

hist(tmp$psi)
quantile(tmp$psi, seq(0,1,0.2))
```


```{r}
# Define PSI categories
VERY_HIGH <- 67.0
MOD_HIGH <- 62.0
NORMAL <- 48.0
MOD_LOW <- 39.0

res <- sentiment.consumer.all %>%
  group_by(#ProductName,
           time = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "month")) %>%
  PSITransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Monthly")
```

# NPS Transitions

```{r}
# Define NPS categories
VERY_HIGH <- 60.0
MOD_HIGH <- 45.0
NORMAL <- 35.0
MOD_LOW <- 8.0
```

## Commercial

### By Week

```{r}

tmp <- survey.comm.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "week")) %>%
   calcNPS()

hist(tmp$nps)
quantile(tmp$nps, seq(0,1,0.2))
```
```{r}
# Define NPS categories
# VERY_HIGH <- 46.0
# MOD_HIGH <- 37.0
# NORMAL <- 34.0
# MOD_LOW <- 30.0

res <- survey.comm.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "week")) %>%
   NPSTransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Weekly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Weekly")
```

### Semi-Monthly

```{r}
tmp <- survey.comm.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "year"),
           week2 = ceiling(week(as.Date(Date.Survey, format = "%m/%d/%Y"))/2)) %>%
  calcNPS()

hist(tmp$nps)
quantile(tmp$nps, seq(0,1,0.2))
```

```{r}
# Define NPS categories
# VERY_HIGH <- 43.0
# MOD_HIGH <- 38.0
# NORMAL <- 36.0
# MOD_LOW <- 31.0

res <- survey.comm.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "year"),
           week2 = ceiling(week(as.Date(Date.Survey, format = "%m/%d/%Y"))/2)) %>%
  NPSTransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Semi-Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Semi-Monthly")
```

### By Month

```{r}

tmp <- survey.comm.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "month")) %>%
   calcNPS()

hist(tmp$nps)
quantile(tmp$nps, seq(0,1,0.2))
```

```{r}
# Define NPS categories
# VERY_HIGH <- 45.0
# MOD_HIGH <- 38.0
# NORMAL <- 35.0
# MOD_LOW <- 32.0

res <- survey.comm.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "month")) %>%
   NPSTransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Commercial, Weekly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Commercial, Weekly")
```

## Consumer

### By Week

```{r}

tmp <- survey.consumer.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "week")) %>%
   calcNPS()

hist(tmp$nps)
quantile(tmp$nps, seq(0,1,0.2))
```

```{r}
# Define NPS categories
# VERY_HIGH <- 41.0
# MOD_HIGH <- 36.0
# NORMAL <- 30.0
# MOD_LOW <- 25.0

res <- survey.consumer.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "week")) %>%
   NPSTransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Consumer, Weekly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Consumer, Weekly")
```

### Semi-Monthly

```{r}
tmp <- survey.consumer.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "year"),
           week2 = ceiling(week(as.Date(Date.Survey, format = "%m/%d/%Y"))/2)) %>%
  calcNPS()

hist(tmp$nps)
quantile(tmp$nps, seq(0,1,0.2))
```

```{r}
# Define NPS categories
# VERY_HIGH <- 42.0
# MOD_HIGH <- 33.0
# NORMAL <- 30.0
# MOD_LOW <- 26.0

res <- survey.consumer.all %>%
  group_by(#ProductName,
           year = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "year"),
           week2 = ceiling(week(as.Date(Date.Survey, format = "%m/%d/%Y"))/2)) %>%
  NPSTransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Consumer, Semi-Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Consumer, Semi-Monthly")
```

### Monthly 

```{r}

tmp <- survey.consumer.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "month")) %>%
   calcNPS()

hist(tmp$nps)
quantile(tmp$nps, seq(0,1,0.2))
```

```{r}
# # Define NPS categories
# VERY_HIGH <- 41.0
# MOD_HIGH <- 30.0
# NORMAL <- 29.0
# MOD_LOW <- 25.0

res <- survey.consumer.all %>%
   group_by(time = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "month")) %>%
   NPSTransitions(VERY_HIGH, MOD_HIGH, NORMAL, MOD_LOW)

knitr::kable(res$P, row.names=TRUE, caption = "P - Consumer, Monthly")

knitr::kable(res$counts, row.names=TRUE, caption = "Counts - Consumer, Monthly")
```
