---
title: "Analysis on Linear Models"
author: "ISE 560"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(out.width = "50%")
knitr::opts_chunk$set(fig.align = "center")

library(tidyverse)
library(xts)
library(tseries)
library(forecast)
source("../src_lenovo_project.R")
source("data_prep.R")
```


```{r}
filter_raw_data()

load("../CleanData/filtered_sentiment_data.Rdata")
load("../CleanData/filtered_survey_data.Rdata")
load("../CleanData/filtered_product_lists.Rdata")

```
```{r}
comm.psi.week <- sentiment.comm %>%
  group_by(week = floor_date(as.Date(Comment.Date, format = "%m/%d/%y"), unit = "week")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE")) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg))

acf(comm.psi.week$psi)
pacf(comm.psi.week$psi)
comm.nps.week <- survey.comm %>%
  group_by(week = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "week")) %>%
  summarise(promoter = sum(NPS >= 9),
            detractor = sum(NPS <= 6),
            total = n()) %>%
  mutate(nps = 100 * (promoter - detractor) / total)
ggplot(comm.psi.week)+geom_line(mapping = aes(x = week,
                                              y = psi))
acf(comm.nps.week$nps)
pacf(comm.nps.week$nps)
```

## Augmented Dickey-Fuller Test

```{r}
nps.xts <- xts(x = comm.nps.week$nps,order.by = comm.nps.week$week)
psi.xts <- xts(x = comm.psi.week$psi,order.by = comm.psi.week$week)
adf.test(nps.xts,alternative = "stationary")
adf.test(psi.xts,alternative = "stationary")
adf.test(diff(psi.xts,na.pad = FALSE),alternative = "stationary")
adf.test(diff(nps.xts,na.pad = FALSE),alternative = "stationary")

```

# ACF 

# PSI after detrending using diff()
Observe that PSI is a 1st order MA process.

```{r}
acf(comm.psi.week$psi) 
pacf(comm.psi.week$psi)
acf(diff(comm.psi.week$psi)) 
pacf(diff(comm.psi.week$psi))
```

# PSI - 2nd order AR process.

```{r}
acf(diff(comm.nps.week$nps)) 
pacf(diff(comm.nps.week$nps))
```

# Covariance with lagged terms

```{r}
merged.df <- merge(comm.nps.week,comm.psi.week,by = "week")

# crosscorr<- 
ccf(merged.df$nps,merged.df$psi)
ccf(diff(merged.df$nps),diff(merged.df$psi))
# NOTE: The lag k value returned by ccf(x, y) estimates the correlation between x[t+k] and y[t].

```

# Test with Auto-Arima 

```{r}
# without cross-correlation
a.arx1 <- auto.arima(merged.df$nps[1:50])
a.arx2 <- auto.arima(merged.df$nps[1:50], xreg = merged.df$psi[1:50])
# with cross-correlation
a.arx3 <- auto.arima(merged.df$nps[1:50], xreg = merged.df$psi[3:52])
m.arx4 <- arima(x = merged.df$nps[1:50],order = c(1,0,1),xreg = merged.df$psi[3:52])
summary(a.arx1)
summary(a.arx2)
summary(a.arx3)
summary(m.armx4)
```

# Residual distributions
```{r}
hist(a.arx1$residuals)
hist(a.arx2$residuals)
hist(a.arx3$residuals)
hist(m.arx4$residuals)
```


# Testing on the same dataset

```{r}
plot(forecast(object = a.arx1,6))
plot(forecast(object = a.arx2,xreg = merged.df$psi[47:52]))
plot(forecast(object = a.arx3,xreg = merged.df$psi[47:52]))
# plot(forecast(object = m.arx4,newxreg = merged.df$psi[47:52]))


```


