---
title: 'Lenovo project: Analysis with telemetry'
---
title: "Lenovo_project"
author: "ISE 560"
date: "10/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("lubridate")
library(ggplot2)
library(cowplot)
source('src_lenovo_project.R')

```

# Extraction

```{r}
nps.main <-read.csv("RawData/Lenovo_Survey_Data_pNPS_Rev2.csv",header = TRUE)
cis.main <- read.csv("RawData/CID_Web_Sentiment.csv", header = TRUE)
battery.life.main <- read.csv("RawData/Battery_Life_hobl.csv", header = TRUE)

nps.main <- nps.main[complete.cases(nps.main$Product),]
cis.main <- cis.main[complete.cases(cis.main$Product),]
# battery.life.main <- battery.life.main[complete.cases(battery.life.main$),]
nps.main <- mutate(nps.main, Product = tolower(as.character(Product)), Date.Survey = as.Date(Date.Survey, format = "%m/%d/%Y"), Ownership.Period = as.character(Ownership.Period))
cis.main <- mutate(cis.main, Product = tolower(as.character(Product)), Comment.Date = as.Date(Comment.Date, format = "%m/%d/%y"), Stars.Rating = as.numeric(Stars.Rating))

# 

```



```{r}
ownership.durations <- c("Less than 3 months", "Between 3 - 6 months", "Between 7 – 12 months","More than 12 months", "Not available")
# Choosing the consumer segment
nps.working <- nps.main[(nps.main$Segment == "Consumer")|(nps.main$Segment == "Lenovo - Consumer"),]#[nps.main$Ownership.Period,]
cis.working <- cis.main[(cis.main$Sentiment == "Consumer")|(nps.main$Segment == "Lenovo - Consumer"),]

#Choosing products that are common to both
product.list = unique(nps.working$Product)
cis.working = cis.working[cis.working$Product %in% product.list,]
product.list = unique(cis.working$Product)
nps.working = nps.working[nps.working$Product %in% product.list,]

nps.working$Product.NPS <- as.numeric(levels(nps.working$Product.NPS))[nps.working$Product.NPS] # Converts factors to numeirc values.

nps.working <- select(nps.working, Date.Survey, Country, Product.NPS, Segment, Product, Ownership.Period)
cis.working <- select(cis.working, comment_id, Comment.Date, Sentiment, Category, Stars.Rating, Business.Group, Product)
# format.type = 1 # For PIS/NPS scores downsampled for each month and product
# format.type = 2 # For PIS/NPS scores downsampled for each product
pis.working <- calculate.PIS(cis.working = cis.working, format.type = 1)
pnps.working <- calculate.NPS(nps.dataset = nps.working, format.type = 1)

```

```{r}
write.csv(pis.working, "RawData/cached_main_pis.csv")
write.csv(pnps.working, "RawData/cached_main_pnps.csv")
write.csv(pis.working[complete.cases(pis.working),], "RawData/cached_main_pis_clean.csv")
write.csv(pnps.working[complete.cases(pnps.working),], "RawData/cached_main_pnps_clean.csv")

```

## Monthly evolution of sentiments

```{r}
pis.working = read.csv("RawData/cached_main_pis.csv")
pnps.working = read.csv("RawData/cached_main_pnps.csv")

pis.working$Comment.time =  ymd(paste0(year_month = as.character(pis.working$Comment.time), day = "30"))
pnps.working$Survey.time =  ymd(paste0(year_month = as.character(pnps.working$Survey.time), day = "30"))


plt.pis.ts <- ggplot(pis.working[], aes(x = Comment.time, y = PIS, color = Product))+geom_line()+ggtitle("Sentiment Time series")+theme(legend.position = "None")

plt.pis.ts

plt.pnps.ts <- ggplot(pnps.working, aes(x = Survey.time, y = pNPS, color = Product))+facet_grid(.~ownership.duration)+geom_line()+ggtitle("NPS Survey time series")+theme(legend.position = "None")

plt.pnps.ts

plt.star.ts <- ggplot(pis.working, aes(x = Comment.time, y = avg.star.rating, color = Product))+geom_line()+geom_point()+ggtitle("Star rating time series")+theme(legend.position = "None")

plt.star.ts

```
## Correlation between CIS and Average Star Rating

```{r}
ggplot(pis.working)+geom_point(aes(x = PIS, y = avg.star.rating))
```



#  Analysis without time information

```{r}
pis.working <- calculate.PIS(cis.working = cis.working, format.type = 2)
pnps.working <- calculate.NPS(nps.dataset = nps.working, format.type = 2)
merged.working = merge(pis.working, pnps.working, by = "Product")
plt.pis <- ggplot(merged.working)+geom_point(aes(x = PIS, y = pNPS))+xlab("PIS")+ggtitle("Average pNPS over all Surveys")+ ylab("pNPS")+facet_grid(.~ownership.duration,scales = "free")
plt.pis
plt.star <- ggplot(merged.working)+geom_point(aes(x = avg.star.rating, y = pNPS))+xlab("Avg. Star Rating")+ggtitle("Average pNPS in the Consumer Segment")+ ylab("pNPS")+facet_grid(.~ownership.duration,scales = "free")
plt.star
```

## Histograms

```{r}
ggplot(pis.working)+geom_histogram(aes(x = PIS),binwidth = 1)
```
  
  
  
  
  