---
title: "Lenovo_project"
author: "ISE 560"
date: "10/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("lubridate")
library(ggplot2)
library(cowplot)
source('src_lenovo_project.R')

```

# Extraction

```{r}
nps.main <-read.csv("RawData/Lenovo_Survey_Data_pNPS_Rev2.csv",header = TRUE)
cis.main <- read.csv("RawData/CID_Web_Sentiment.csv", header = TRUE)
battery.life.main <- read.csv("RawData/Battery Life.csv", header = TRUE)
ownership.durations <- c("Less than 3 months","More than 12 months","Between 3 – 6 months","Between 7 – 12 months")

nps.main <- nps.main[complete.cases(nps.main$Product),]
cis.main <- cis.main[complete.cases(cis.main$Product),]
nps.main <- mutate(nps.main, Product = tolower(as.character(Product)), Date.Survey = as.Date(Date.Survey, format = "%m/%d/%Y"), Ownership.Period = as.character(Ownership.Period), Product.NPS = as.numeric(levels(Product.NPS))[Product.NPS])
cis.main <- mutate(cis.main, Product = tolower(as.character(Product)), Comment.Date = as.Date(Comment.Date, format = "%m/%d/%y"), Stars.Rating = as.numeric(Stars.Rating))

# Choosing the consumer segment
nps.main <- nps.main[(nps.main$Segment == "Consumer")|(nps.main$Segment == "Lenovo - Consumer"),]#[nps.main$Ownership.Period,]
cis.main <- cis.main %>% filter(Business.Group  == "LENOVO - CONSUMER")

#Choosing products that are common to both
product.list = unique(nps.main$Product)
cis.main = cis.main[cis.main$Product %in% product.list,]
product.list = unique(cis.main$Product)
nps.main = nps.main[nps.main$Product %in% product.list,]
unique(nps.main$Ownership.Period)
```

# Calcualte pNPS according to week

```{r}
pnps.working.week.all <- data.frame()
for(duration in ownership.durations){
  pnps.working.week.all <- pnps.working.week.all %>%
    rbind(nps.main[nps.main$Ownership.Period==duration,]%>%
            group_by(week = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "week")) %>%
            summarise(promoter = sum(Product.NPS >= 9),
                      detractor = sum(Product.NPS <= 6),
                      total = n()) %>%
            mutate(nps = 100 * (promoter - detractor) / total,
                   Ownership.period = duration))
}

psi.working.week.all <- cis.main %>%
  group_by(week = floor_date(Comment.Date, unit = "week")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE"),
            pos.star = sum(Stars.Rating <3),
            neg.star = sum(Stars.Rating>3),
            total = n()) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg),
         star.index = 100*(pos.star - neg.star)/(total))
```

# Calcualte pNPS according to Month

```{r}
pnps.working.month.all <- data.frame()
for(duration in ownership.durations){
  pnps.working.month.all <- pnps.working.month.all %>%
    rbind(nps.main[nps.main$Ownership.Period==duration,]%>%
            group_by(month = floor_date(as.Date(Date.Survey, format = "%m/%d/%Y"), unit = "month")) %>%
            summarise(promoter = sum(Product.NPS >= 9),
                      detractor = sum(Product.NPS <= 6),
                      total = n()) %>%
            mutate(nps = 100 * (promoter - detractor) / total,
                   Ownership.period = duration))
}

psi.working.month.all <- cis.main %>%
  group_by(month = floor_date(Comment.Date, unit = "month")) %>%
  summarise(pos = sum(Sentiment == "POSITIVE"),
            neg = sum(Sentiment == "NEGATIVE"),
            pos.star = sum(Stars.Rating <3),
            neg.star = sum(Stars.Rating>3),
            total = n()) %>%
  mutate(psi = 100 * (pos - neg)/(pos +  neg),
         star.index = 100*(pos.star - neg.star)/(pos+neg))
```

```{r}

plt <- ggplot() +
  geom_line(data = pnps.working.month.all, mapping = aes(x=month, y=nps, color="NPS")) +
  geom_line(data = psi.working.month.all, mapping = aes(x=month, y=psi, color="PSI"))+
  geom_line(data = psi.working.month.all, mapping = aes(x=month, y=star.index, color="Star Index"))+
  facet_wrap(.~Ownership.period,nrow = 2)+
  labs(title="NPS, PSI and Star Rating for All Consumer Products", color = "Metrics:")+ylab("")+xlab("Time")+
  theme(legend.position = "bottom")
ggsave(plot = plt,filename = "Proposal/Figures/all_metric_summary_consumer.pdf",width = 8, height = 5,units = "in")
```


## Autocorrelation of Metrics based on series
We calcualte the ACF of the 
```{r}

```



## Monthly evolution of sentiments

```{r}
psi.working = read.csv("RawData/cached_main_psi.csv")
pnps.working = read.csv("RawData/cached_main_pnps.csv")

psi.working$Comment.time =  ymd(paste0(year_month = as.character(psi.working$Comment.time), day = "30"))
pnps.working$Survey.time =  ymd(paste0(year_month = as.character(pnps.working$Survey.time), day = "30"))


```
## Correlation between CIS and Average Star Rating

```{r}
ggplot(psi.working)+geom_point(aes(x = psi, y = avg.star.rating))
```



#  Analysis without time information

```{r}
psi.working <- calculate.psi(cis.working = cis.working, format.type = 2)
pnps.working <- calculate.NPS(nps.dataset = nps.working, format.type = 2)
merged.working = merge(psi.working, pnps.working, by = "Product")
plt.psi <- ggplot(merged.working)+geom_point(aes(x = psi, y = pNPS))+xlab("psi")+ggtitle("Average pNPS over all Surveys")+ ylab("pNPS")+facet_grid(.~ownership.duration,scales = "free")
plt.psi
plt.star <- ggplot(merged.working)+geom_point(aes(x = avg.star.rating, y = pNPS))+xlab("Avg. Star Rating")+ggtitle("Average pNPS in the Consumer Segment")+ ylab("pNPS")+facet_grid(.~ownership.duration,scales = "free")
plt.star
```

## Histograms

```{r}
ggplot(psi.working)+geom_histogram(aes(x = psi),binwidth = 1)
```
  
  
  
  
  