---
title: "ISE 560 Project Proposal"
author: "Shawn Markham, Melissa Wong, Shrikanth Yadav & Lekhana Yennam"
date: \today
header-includes:
   - \usepackage{fontspec}
   - \setmainfont{Times New Roman}
output: 
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    fig_caption: true
fontsize: 12pt
geometry: margin=1in 
---

```{r echo=FALSE, results='hide', message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(out.width="50%")
knitr::opts_chunk$set(fig.align = "center")

library(tidyverse)
```

# Overview

## Model

## Metrics

# NPS & Telemetry
   Net Promotor Score (NPS) is a management tool that measures customer satisfaction, as well as customer loyalty. The score is based entirely on the customer’s response to the question “How likely are you to recommend this product (or service) to someone else?” Their response is a number on the scale of zero (being the least likely) to ten (being the most likely). Companies then categorize the customer’s based off the scores they inputted. If a customer’s NPS response score was between a nine and a ten, the customer is called a promoter. If the customer’s response was low, between zero and six, they are called a detractor. The company’s NPS score is calculated by subtracting the percentage of detractors from the percentage of promoters. 
   Every industry has a different NPS average and this number can give company’s a good indication of how loyal their customers are compared to other companies. Customer loyalty is crucial because companies spend less money keeping current customers than marketing to attract new customers. Within the laptop and tablet industry, the average NPS score is a 40. Apple has the most loyal and satisfied customers according the net promoter score. Their NPV score is a 68. Lenovo is above the industry average of 40 but they need to use customer reviews and telemetry data to make changes to their products in order to beat Apple.
   Telemetry data is system performance data that is captured as soon as a device is turned on. This data captured by Microsoft and then sent to Lenovo. Lenovo can then analyze this data to determine meaningful information about their machines. Telemetry is crucial within the laptop industry because it gives companies insight on which features their customers are using the most, enabling them to determine the most important features and shape future models based off of these statistics. Analyzing Telemetry data can also help Lenovo determine which devices are malfunctioning or experiencing bugs. For instance, if the data shows that seventy percent of Lenovo ThinkPad’s are crashing every two hours, Lenovo may need to provide some type of update or even recall the machine. In this same example where a customer is experiencing crashes every two hours, it is likely that they will answer the question “How likely are you to recommend this product (or service) to someone else?” with a low NPS score and be identified as a detractor. For this reason, telemetry has a great potential for predicting NPS score and we will incorporate the driver, battery, and Wi-Fi connectivity data findings into our models. 


# Key Variables and Parameters
The models created will be based off of several variables including the evolution of sentiment, stars, business class, and product family. 
Parameters?

# Critical Uncertainties

# Markov Decision Process

# Preliminary Data Analysis

Segment    | Total Products | Products w/both Sentiment and NPS | w/Battery | w/Wifi | w/Driver Reliabity
---------- | -------------- | -------------------- | ------- | ---- | -----------
Consumer   | TBD            |      73              | TBD     | TBD  |     TBD
Commercial | 238            |      46              | TBD     | TBD  |     TBD
SMB        |   59           |      18              | TBD     | TBD  |     TBD

## Customer Sentiment

## Telemetry